export const NTFY_CONFIG = {
  enabled: true,
  secureStorageKey: 'ntfy-installation-v2',
  legacySecureStorageKey: 'ntfy-installation-v1',
  secureStoragePrefix: 'blinker_',
  provisionRetryDelaysMs: [1_000, 2_000, 4_000, 8_000] as const,
  revokeRetryDelaysMs: [1_000, 2_000, 4_000, 8_000] as const,
  maxConflictRotations: 1,
  maxRetryDelayMs: 30_000,
  initialSince: '10m',
  autoStartOnBoot: true,
  showNotifications: true,
  historyLimit: 50,
  foregroundTitle: 'blinker 消息服务',
  foregroundText: '正在接收站内信提醒',
  serviceChannelId: 'blinker_ntfy_service',
  serviceChannelName: 'blinker 消息服务',
  messageChannelId: 'blinker_ntfy_messages',
  messageChannelName: 'blinker 消息提醒',
} as const;
