name: CI&&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Dependent environment
        run: |
          npm i -g @angular/cli
          npm i --force
      
      - name: Compile
        run: |
          npm run build
      
      - name: Compress files
        run: |
          tar -czf dist.tar.gz www/
        
      - name: Upload and deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist.tar.gz"
          target: "/tmp"
          strip_components: 0

      - name: Extract files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p ${{ secrets.TARGET }}
            tar -xzf /tmp/dist.tar.gz -C ${{ secrets.TARGET }} --strip-components=1
            rm /tmp/dist.tar.gz
